# Generated by Django 5.0.7 on 2024-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_alter_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('Attrition', models.CharField(max_length=255)),
                ('BusinessTravel', models.CharField(max_length=255)),
                ('DailyRate', models.FloatField()),
                ('Department', models.CharField(max_length=255)),
                ('DistanceFromHome', models.FloatField()),
                ('Education', models.FloatField()),
                ('EducationField', models.CharField(max_length=255)),
                ('EmployeeCount', models.FloatField()),
                ('EmployeeNumber', models.FloatField()),
                ('EnvironmentSatisfaction', models.FloatField()),
                ('Gender', models.CharField(max_length=255)),
                ('HourlyRate', models.FloatField()),
                ('JobInvolvement', models.FloatField()),
                ('JobLevel', models.FloatField()),
                ('JobRole', models.CharField(max_length=255)),
                ('JobSatisfaction', models.FloatField()),
                ('MaritalStatus', models.CharField(max_length=255)),
                ('MonthlyIncome', models.FloatField()),
                ('MonthlyRate', models.FloatField()),
                ('NumCompaniesWorked', models.FloatField()),
                ('Over18', models.CharField(max_length=255)),
                ('OverTime', models.CharField(max_length=255)),
                ('PercentSalaryHike', models.FloatField()),
                ('PerformanceRating', models.FloatField()),
                ('RelationshipSatisfaction', models.FloatField()),
                ('StandardHours', models.FloatField()),
                ('StockOptionLevel', models.FloatField()),
                ('TotalWorkingYears', models.FloatField()),
                ('TrainingTimesLastYear', models.FloatField()),
                ('WorkLifeBalance', models.FloatField()),
                ('YearsAtCompany', models.FloatField()),
                ('YearsInCurrentRole', models.FloatField()),
                ('YearsSinceLastPromotion', models.FloatField()),
                ('YearsWithCurrManager', models.FloatField()),
            ],
        ),
    ]
